### ISSUE TITLE
Notes from the Data Trainers Catch up web conference on Friday Feb 16, 2018

### ISSUE THREAD

**Issue by GerryRyder** [rowlandm/research_trainers_oz#11]
[Notes](https://docs.google.com/document/d/1N_4-WnChfmvuobjw_0JpmpdhSHRjtgrfTTZfck_QcUE/edit) from the Data Trainers Catch Up web conference on Friday Feb 16, 2018.

Please add to, or amend them.

**Comment by rowlandm** [comment]
Thanks Gerry - that's very detailed!!!!
