### ISSUE TITLE
Regular meetings every month

### ISSUE THREAD

**Issue by rowlandm** [rowlandm/research_trainers_oz#12]
Hi All,

To try and keep the momentum going, we should probably have regular meetings to share ideas around a specific topic.

I would suggest that we have them on the second Friday of every month around 11am - would that suit most people? 

Also please have a look at what was talked about in the November meeting or any other issues that were created and if something is of interest, create an issue based off that topic:
https://github.com/rowlandm/research_trainers_oz/issues/2

For example, an issue around champions should definitely be created as this is in most DEVL/RDC skills focuses. But it's up to the community to lead this, not myself - so if this is a topic you would like to dive deep into, then create an issue.

The issue that gets the most comments will probably be the one we want to discuss first.

A reminder that if you want to subscribe to all updates read here to work out how to watch this repository:
https://help.github.com/articles/watching-and-unwatching-repositories/#watching-a-single-repository

**Comment by KateLeMay** [comment]
Yes Fridays at 11am suit me. :)

**Comment by GerryRyder** [comment]
That time works for me too

**Comment by chuijbers** [comment]
Completely support a fixed day/time for a monthly meeting. It would be good to have one or two topics to discuss each meeting so people can opt in/out based on their interest. So maybe we should start a list with potential topics (based on the issues list?) and pick which ones will be discussed in the next meeting.

**Comment by squarcleconsulting** [comment]
I am good with Friday at 11:00am.  Can I also suggest that we rotation the facilitator/chair for each meeting?

**Comment by AnnaSyme** [comment]
That time works for me.

**Comment by rowlandm** [comment]
Yes, that's right Anna.

Happy to rotate the facilitator/chair. Does anyone want to volunteer? I think we haven't got much input from the community via this github and I'm wondering if people can start to put in comments on this thread about what they wanted to discuss.
