### ISSUE TITLE
Next meeting: Friday March 9th at 11am

### ISSUE THREAD

**Issue by rowlandm** [rowlandm/research_trainers_oz#14]
Next meeting is on Friday the 9th of March at 11am.

We need:
- a couple of topics to discuss
- a facilitator

Pleast put in the comments what you would like to discuss and if you would like to put your hand up as a facilitator.

A reminder that if you want to subscribe to all updates read here to work out how to watch this repository:
https://help.github.com/articles/watching-and-unwatching-repositories/#watching-a-single-repository

**Comment by squarcleconsulting** [comment]
I am happy to talk about the Research Training Implement Plan released by the government late last for the next meeting.

**Comment by andrewjanke** [comment]
Sorry, won't be able to make this one.

**Comment by robertshen-aal** [comment]
Where to find out the zoom meeting details?

**Comment by rowlandm** [comment]
We can use https://unimelb.zoom.us/j/6552003787

But I would be happy to skip this meeting if we didn't get much feedback from the community about what they wanted to hear about.

**Comment by GerryRyder** [comment]
I'd be interested to hear about the Research Training Implementation Plan and how/if anyone in this group is responding.  Also, current/future training priorities for group members would be of interest as we might be able to identify some common threads.

**Comment by lancewilson-monash** [comment]
Sorry, won't be able to make this one

**Comment by rowlandm** [comment]
Hi All,

For anyone who wants to join the meeting tomorrow, 11 am (NSW/ACT/VIC time), the new zoom meeting will be:
https://aarnet.zoom.us/j/8333641713
